// Generated by https://quicktype.io

import 'package:json_annotation/json_annotation.dart';

part 'like_model.g.dart';

@JsonSerializable()
class LikeModel {
  final String contentType;
  final String contentId;

  LikeModel({
    required this.contentType,
    required this.contentId,
  });

  factory LikeModel.fromJson(Map<String,dynamic> json) => _$LikeModelFromJson(json);

  Map<String, dynamic> toJson() => _$LikeModelToJson(this);
}
