 // Generated by https://quicktype.io

import 'package:dd_study_ui/domain/models/post_content.dart';
import 'package:json_annotation/json_annotation.dart';

import 'user.dart';

part 'post_model.g.dart';


@JsonSerializable()
class PostModel {
  List<PostContent> attaches;
  String id;
  String? text;
  String? created;
  User user;
  int comments;
  int likes;

  PostModel({
    required this.id,
    required this.attaches,
    this.text,
    this.created,
    required this.user,
    required this.comments,
    required this.likes,
  });

  factory PostModel.fromJson(Map<String,dynamic> json) => _$PostModelFromJson(json);

  Map<String, dynamic> toJson() => _$PostModelToJson(this);
}

