// Generated by https://quicktype.io

import 'package:json_annotation/json_annotation.dart';
part 'register_model.g.dart';

@JsonSerializable()
class RegisterModel {
  final String name;
  final String email;
  final String password;
  final String retryPassword;
  final String birthDate;

  RegisterModel({
    required this.name,
    required this.email,
    required this.password,
    required this.retryPassword,
    required this.birthDate,
  });

  factory RegisterModel.froomJson(Map<String,dynamic> json) => _$RegisterModelFromJson(json);
  Map<String, dynamic> toJson() => _$RegisterModelToJson(this);
  
}
