// Generated by https://quicktype.io

import 'package:json_annotation/json_annotation.dart';

part 'settings_model.g.dart';

@JsonSerializable()
class PrivacySettingsModel {
  final int avatarAccess;
  final int postAccess;
  final int messageAccess;
  final int commentAccess;

  PrivacySettingsModel({
    required this.avatarAccess,
    required this.postAccess,
    required this.messageAccess,
    required this.commentAccess,
  });

  factory PrivacySettingsModel.fromJson(Map<String,dynamic> json) => _$PrivacySettingsModelFromJson(json);

  Map<String, dynamic> toJson() => _$PrivacySettingsModelToJson(this);
}
