// Generated by https://quicktype.io
import 'package:json_annotation/json_annotation.dart';

part 'user.g.dart';

@JsonSerializable()
class User {
  final String avatar;
  final String id;
  final String name;
  final String email;
  final String birthDate;

  User({
    required this.avatar,
    required this.id,
    required this.name,
    required this.email,
    required this.birthDate,
  });

  factory User.fromJson(Map<String,dynamic> json) => _$UserFromJson(json);

  Map<String, dynamic> toJson() => _$UserToJson(this);
}
