// Generated by https://quicktype.io
import 'package:dd_study_ui/domain/db_model.dart';
import 'package:json_annotation/json_annotation.dart';

part 'user.g.dart';

@JsonSerializable()
class User implements DbModel{
  @override
  final String id;
  final String avatar;
  final String name;
  final String email;
  final String birthDate;

  User({
    required this.avatar,
    required this.id,
    required this.name,
    required this.email,
    required this.birthDate,
  });

  factory User.fromJson(Map<String,dynamic> json) => _$UserFromJson(json);

  Map<String, dynamic> toJson() => _$UserToJson(this);

  @override 
  Map<String,dynamic> toMap() => _$UserToJson(this);

  factory User.fromMap(Map<String, dynamic> map) => _$UserFromJson(map);

  @override 
  bool operator == (Object other)
  {
    if(identical(this, other)) return true;

    return other is User &&
    other.id == id &&
    other.name == name &&
    other.email == email &&
    other.birthDate == birthDate &&
    other.avatar == avatar;
  }
  @override 
  int get hashCode
  {
    return id.hashCode ^
    name.hashCode ^
    email.hashCode ^
    birthDate.hashCode ^
    avatar.hashCode;
  }
}
